default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rama-development
  # username: root
  # password: root

test:
  <<: *default
  database: rama-test
  # username: root
  # password: root

production:
  <<: *default
  database: rama-production
  # username: rama
  # password: Rails.application.secrets[:production][:password]
